### ISSUE TITLE
curated list of y-coordinate col names for boxplot

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEPDataExplorer#1]

**Comment by kdaily** [comment]
From Mark:

Features for boxplots
X axis  Factors
ECMp or Ligand

Points within the boxplots should be the factor not used on the x axis

Y Variables
Spot_PA_SpotCellCountLog2
Spot_PA_SpotCellCountLog2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_MitoTrackerLog2RUV3Loess
Nuclei_CP_Intensity_MedianIntensity_EdULog2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_KRT19Log2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_KRT5Log2RUV3Loess
Nuclei_PA_Cycle_DNA2NProportionLogitRUV3Loess
Nuclei_PA_Gated_EdUPositiveProportionLogitRUV3LoessBacktransformed
Nuclei_PA_Cycle_DNA2NProportionLogitRUV3LoessBacktransformed

**Comment by kdaily** [comment]
The following columns are not available in level 4 data files:
- Cytoplasm_CP_Intensity_MedianIntensity_MitoTrackerLog2RUV3Loess
- Nuclei_CP_Intensity_MedianIntensity_EdULog2RUV3Loess
- Cytoplasm_CP_Intensity_MedianIntensity_KRT19Log2RUV3Loess
- Cytoplasm_CP_Intensity_MedianIntensity_KRT5Log2RUV3Loess
- Nuclei_PA_Gated_EdUPositiveProportionLogitRUV3LoessBacktransformed
- Nuclei_PA_Cycle_DNA2NProportionLogitRUV3LoessBacktransformed

**Comment by markdane** [comment]
The file at syn7187256 has a list of columns in the MCF10A SSC (syn7122655) data that should be displayed by the Shiny App.

**Comment by kdaily** [comment]
Great, thanks! Will give this a try.

**Comment by markdane** [comment]
I've updated the CuratedFeatures file to include the transformation info in the display names.
