### ISSUE TITLE
Make 12-Sept-2016 release public

### ISSUE THREAD

**Issue by markdane** [MEP-LINCS/MEPDataExplorer#11]
The explorer, data and reports are ready to be made public. It would be nice to add a data manifest table but we don't need to hold the release up for that. Can you move this into the proper area or let me know what to do?

**Comment by markdane** [comment]
I jumped the gun here.....

**Comment by kdaily** [comment]
Didn't hear back about what to do re: versions being at 5 on all the files? Can't be changed as it reflects the true history.

**Comment by markdane** [comment]
Reopened to address issue on version.

I think these should be released to the public at version 1. If that means uploading them to new synIDs after the F2F, that's ok. I can do that.

**Comment by kdaily** [comment]
Yeah, that's what it will mean (and regenerating the provenance relationships as well).
