### ISSUE TITLE
curated list of x and y columns for plotly scatterplot

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEPDataExplorer#2]

**Comment by markdane** [comment]
Colour Factors
ECMp Ligand

X and Y Variables
Spot_PA_SpotCellCountLog2
Spot_PA_SpotCellCountLog2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_MitoTrackerLog2RUV3Loess
Nuclei_CP_Intensity_MedianIntensity_EdULog2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_KRT19Log2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_KRT5Log2RUV3Loess
Nuclei_PA_Cycle_DNA2NProportionLogitRUV3Loess
Nuclei_PA_Gated_EdUPositiveProportionLogitRUV3LoessBacktransformed
Nuclei_PA_Cycle_DNA2NProportionLogitRUV3LoessBacktransformed

**Comment by markdane** [comment]
Features for boxplots
X axis  Factors
ECMp or Ligand

Points within the boxplots should be the factor not used on the x axis

Y Variables
Spot_PA_SpotCellCountLog2
Spot_PA_SpotCellCountLog2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_MitoTrackerLog2RUV3Loess
Nuclei_CP_Intensity_MedianIntensity_EdULog2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_KRT19Log2RUV3Loess
Cytoplasm_CP_Intensity_MedianIntensity_KRT5Log2RUV3Loess
Nuclei_PA_Cycle_DNA2NProportionLogitRUV3Loess
Nuclei_PA_Gated_EdUPositiveProportionLogitRUV3LoessBacktransformed
Nuclei_PA_Cycle_DNA2NProportionLogitRUV3LoessBacktransformed

Thanks,

Mark

**Comment by kdaily** [comment]
Only:
- Nuclei_PA_Cycle_DNA2NProportionLogitRUV3Loess
- Spot_PA_SpotCellCountLog2RUV3Loess

are available.

**Comment by markdane** [comment]
Kenny,

Sorry about breaking your code by leaving out many features. I found and fixed the problem in my code and updated the SSC files on Synapse. Now the curated features to be displayed are in the files except for the back transformed versions. I’m hoping you can back transform them with the function I sent you previously.

Mark

**Comment by kdaily** [comment]
Thanks!

Not sure I understand what to do re: backtransforming columns? Can you provide an example of how to use the code to update the data frame (e.g., which column goes in, what to name the resulting column)?

**Comment by markdane** [comment]
The btlogit function can be applied within the ggplot function.
p <- ggplot(dt, aes(x=Ligand, y=btLogit(Nuclei_PA_Cycle_DNA4NProportionLogitRUV3Loess))+
  geom_boxplot(outlier.colour = NA, alpha=.5)
This leaves the issue of the ugly, long names. We're going to talk about that tomorrow but I think we'll really want a description of the signal that's visible when the column is selected. Any idea about how to track and display that?

**Comment by kdaily** [comment]
OK, I see what you mean - but that only works for that column. It would be cumbersome to detect if the user had selected that specific column and then apply the function - what if they select `Spot_PA_SpotCellCountLog2`?

**Comment by kdaily** [comment]
For the names, it's pretty easy to set up a mapping between the long name and a name for viewing (just a data frame). Then lookup the name to use for x/y labeling, etc.

**Comment by markdane** [comment]
It would need to detect when logit is in the column name. The alternative is to add backtransformed versions of the columns to the dataset. I'm currently keeping intermediate versions of the features as they are calculated. Some have proven useful but many can be deleted. It's likely time for me to curate this down to the one's I think users will find valuable. 

I'll decide on that soon.

**Comment by markdane** [comment]
Let's plan on having a feature name dataframe that includes long names, display names and descriptions. Do you think the description could conditionally appear when the feature is used in a figure?

**Comment by kdaily** [comment]
Probably, as a title of the figure?

**Comment by markdane** [comment]
I'm thinking the description is specific to the column and may be several sentences covering method used to calculate it and usage considerations. Ideally, it would appear when hovering over the short name though I don't know if that's possible. Otherwise, maybe it is displayed in a text box somewhere in the figure.

**Comment by kdaily** [comment]
Easy to have it displayed in the app, more difficult to put it in the figure (placement in dynamically drawn figures is always hard). Can start with the former and worry about it later!

Keeping a Synapse table of column info would be good (like https://www.synapse.org/#!Synapse:syn5662377 for annotations). That way, column info can also be displayed in the Wiki.

**Comment by markdane** [comment]
Closing based on having a valid CuratedFeatures file
