### ISSUE TITLE
New data files can't be read in R

### ISSUE THREAD

**Issue by kdaily** [MEP-LINCS/MEPDataExplorer#4]
I get the following:

```
> d <- synGet('syn7122655')
> d@properties$versionNumber
[1] 2
> d <- read.csv(getFileLocation(d))
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names
```

**Comment by markdane** [comment]
These files use a tab as a delimiter so it needs to be explicitly defined. 
 d <- read.csv(getFileLocation(d), sep = "\t")

**Comment by kdaily** [comment]
Doesn't work. If I do that, I get:

```
> d <- read.table(getFileLocation(d), sep="\t")
> dim(d)
[1] 2737    1
```

Reads each row as one column.

`data.table` complains of this:

```
> dt <- fread(getFileLocation(d), sep="\t", data.table=FALSE)
Error in fread(getFileLocation(d), sep = "\t", data.table = FALSE) : 
  The supplied 'sep' was not found on line 30. To read the file as a single character column set sep='\n'.
```

**Comment by kdaily** [comment]
Confirmed that version 1 of this file works OK:

```
> d <- synGet('syn7122655', version=1)
> dt <- read.table(getFileLocation(d), sep="\t")
> dim(dt)
[1] 8161  348
```

**Comment by markdane** [comment]
Sorry about that. I added some metadata that I read from excel files and the values contained commas. Now the HMEC122L and HMEC240L level 4 files have tab delimiters and read correctly

> d <- synGet("syn7122641")
> d <- read.csv(getFileLocation(d),sep="\t")
> dim(d)
> [1] 2736 1053
> I'll need a bit more time to get to the MCF10A and level 3 files

**Comment by markdane** [comment]
New level 3 and level 4 data files and reports for all threes cell lines are on Synapse. SS1, SS2, SS3, and SS4 are single staining set data sets. SSC combines the DAPI signals that are common to all staining sets with the signals (KRTs, EdU, MitoTacker) that are unique to the numbered staining sets. The Level 4 SSC is the appropriate data set to begin exploration.

A new file in the Annotated Data directory is a prototype for a file that provides a display name and description for each curated feature. The display name can be used to label the axis in figure. Ideally, eventually the description appears in a tool tip hover box.

We are beginning to develop this feature data with the intention that it be used in several applications. Its format and content are subject to change and I'd like any feedback on it.

**Comment by kdaily** [comment]
What happened to the column `StainingSet` in the combined (`SSC`) files? The Shiny app relies on that to filter the SSC for the staining set the user is interested in.

**Comment by markdane** [comment]
I moved StainingSet from within the file to an annotation. Sorry about doing that with no warning. I did that as part of the general cleanup without realizing what t would do to your code,

It's also in the filename. Do you think it's appropriate as an annotation or should go back into the data table?

**Comment by kdaily** [comment]
I think it would be useful to have that in the SSC data for users to know
which staining set they came from, but not necessarily in each if the
individual staining set files (SS1-SS4, for example).

**Comment by markdane** [comment]
In the level 4 SSC files, each row is a MEP and it has data from 2 or 3 staining sets so there's not a tidy way to let the user know which staining set a feature came from.

It would be meaningful in the level 3 SSC files but I don't know if anyone (besides me) will use these and I don't plan for us to put time into visualizations for them.

**Comment by kdaily** [comment]
Hmm. So how will the filter I have work that works on staining set? Do you
not want that and only want Ligand?

**Comment by markdane** [comment]
Yes, please delete the staining set filter. That would leave us with a cell line selector, right?
